default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements

- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]      
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
    - id: commitizen
      name: commitizen check
      entry: cz check
      language: python
      language_version: python3
      args: [--allow-abort, --commit-msg-file]
      stages: [commit-msg]
