# Use root/example as user/password credentials
version: '3.8'

# exposing ports is informative, all services in this network are going to see 
# the exposed ports anyway
services:
  mongo:
    image: mongo:4.4.20-focal
    networks:
      main:
        ipv4_address: 190.20.0.0
    expose:
      - '27017'
    volumes:
      - mongo_volume:/data/db
    command: mongod --quiet --logpath /dev/null
    container_name: mongo_container
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
  cnmv_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: cnmv_service
    networks:
      - main
    ports:
      - '8081:8080'
    depends_on:
      mongo:
        condition: service_healthy
    command: python src/service.py
    environment:
      - MONGO_HOST=190.20.0.0
      - SERVICE_HOST=0.0.0.0
    container_name: cnmv_service_container
    volumes:
      - cnmv_logs:/cnmv

networks:
  main:
    ipam:
      config:
        - subnet: 190.20.0.0/10

volumes:
  mongo_volume:
  cnmv_logs:
